name: mlops-basics-development

services:
  mlops-basics-development:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - USER_NAME=${USER_NAME:-vscode}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    image: ${COMPOSE_PROJECT_NAME}-development
    container_name: ${COMPOSE_PROJECT_NAME}-development
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./.ssh
        target: /home/${USER_NAME}/.ssh
    ports:
      - "6006:6006" # tensorboard
      - "8000:8000" # fastapi
    user: ${USER_NAME:-vscode}
    tty: true
