name: mlops-basics-development

services:
  mlops-basics-development:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - IMAGE_NAME=${IMAGE_NAME:-python:3.11.9-slim-bullseye}
        - SLIM_IMAGE_NAME=${SLIM_IMAGE_NAME:-python:3.11.9-slim-bullseye}
        - USER_NAME=${USER_NAME:-vscode}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    image: ${COMPOSE_PROJECT_NAME}-development:${TAGS}
    container_name: ${COMPOSE_PROJECT_NAME}-development
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./.ssh
        target: /home/${USER_NAME}/.ssh
    ports:
      - "6006:6006" # tensorboard
      - "8000:8000" # fastapi
      - "8080:8080" # dvc[gdrive]
    user: ${USER_NAME:-vscode}
    tty: true
