name: mlops-basics-deploy

services:
  mlops-basics-deploy:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    image: ${COMPOSE_PROJECT_NAME}-deploy
    container_name: ${COMPOSE_PROJECT_NAME}-deploy
    ports:
      - "8000:8000" # fastapi
    tty: true
